In [9]:
X = [[1], [2], [3], [4], [5]]
y = [10, 20, 30, 40, 50]
from sklearn.model_selection import train_test_split

X_train, Y_train, x_test, y_test = train_test_split(X, y, test_size=0.2, random_state=7)
print(x_test, y_test,X_train,Y_train)

[40, 30, 20, 50] [10] [[4], [3], [2], [5]] [[1]]


In [10]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
import numpy as np
data = np.array([[10], [20], [30]])
print(MinMaxScaler().fit_transform(data))
print(StandardScaler().fit_transform(data))

[[0. ]
 [0.5]
 [1. ]]
[[-1.22474487]
 [ 0.        ]
 [ 1.22474487]]


In [11]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
import numpy as np

cities = np.array([["NY"], ["LA"], ["Chicago"]])
encoder = OneHotEncoder()
print(encoder.fit_transform(cities).toarray())  # One-hot encoded

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [48]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "name": ["Alice", "Bob", "Charlie"],
    "age": [25, np.nan, 30]
})
df["age"] = df["age"].fillna(df["age"].mean())    # Mean
df["age"] = df["age"].fillna(df["age"].median())  # Median

print(df)
print()



      name   age
0    Alice  25.0
1      Bob  27.5
2  Charlie  30.0



In [37]:
df = pd.DataFrame({"height": [1.6, 1.8], "weight": [60, 80]})
df["BMI"] = df["weight"] / (df["height"] ** 2)
print(df)


   height  weight        BMI
0     1.6      60  23.437500
1     1.8      80  24.691358


In [38]:
import re
text = "Hello, AI!!!"
cleaned = re.sub(r"[^a-zA-Z\s]", "", text).lower()
print(cleaned)  # 'hello ai'

hello ai


In [39]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

df = pd.DataFrame({"height": [150, 160, 170], "weight": [50, 60, 80]})
scaler = MinMaxScaler()
df_scaled = pd.DataFrame(scaler.fit_transform(df), columns=df.columns)
print(df_scaled)

   height    weight
0     0.0  0.000000
1     0.5  0.333333
2     1.0  1.000000
