In [2]:
import numpy as np

arr = np.array([[5, 10, 15],
                [20, 25, 30],
                [35, 40, 45]])

In [21]:
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr[:-1:1])
print(np.min(arr))
print(np.max(arr))
print(np.median(arr))
print(np.std(arr))
print(arr*2)

(3, 3)
9
int32
[[ 5 10 15]
 [20 25 30]]
5
45
25.0
12.909944487358056
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [23]:
import pandas as pd

data = {
    "name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "age": [25, 30, 35, None, 40],
    "city": ["NY", "LA", "NY", "Chicago", "LA"]
}
df = pd.DataFrame(data)
print(df)

      name   age     city
0    Alice  25.0       NY
1      Bob  30.0       LA
2  Charlie  35.0       NY
3    David   NaN  Chicago
4      Eva  40.0       LA


In [28]:
print(df.head(3))
print()
print(df[["name", "city"]])
print()
print(df[df["age"] > 30])
print()
df["age"] = df["age"].fillna(0)
print(df)
print()
print(df.groupby("city")["age"].mean())

      name   age city
0    Alice  25.0   NY
1      Bob  30.0   LA
2  Charlie  35.0   NY

      name     city
0    Alice       NY
1      Bob       LA
2  Charlie       NY
3    David  Chicago
4      Eva       LA

      name   age city
2  Charlie  35.0   NY
4      Eva  40.0   LA

      name   age     city
0    Alice  25.0       NY
1      Bob  30.0       LA
2  Charlie  35.0       NY
3    David   0.0  Chicago
4      Eva  40.0       LA

city
Chicago     0.0
LA         35.0
NY         30.0
Name: age, dtype: float64
